CREATE TABLE tasks (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(100) NOT NULL,
    description  VARCHAR(500),
    completed    BOOLEAN      NOT NULL DEFAULT FALSE,
    due_date     DATE,
    priority     VARCHAR(16)  NOT NULL,
    created_at   TIMESTAMP    NOT NULL,
    updated_at   TIMESTAMP
);

CREATE TABLE task_tags (
    task_id BIGINT       NOT NULL,
    tag     VARCHAR(64)  NOT NULL,
    CONSTRAINT pk_task_tags PRIMARY KEY (task_id, tag),
    CONSTRAINT fk_task_tags_task FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE
);

CREATE TABLE task_attachments (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id           BIGINT       NOT NULL,
    file_name         VARCHAR(255) NOT NULL,
    stored_file_name  VARCHAR(255) NOT NULL,
    content_type      VARCHAR(255),
    size              BIGINT       NOT NULL,
    uploaded_at       TIMESTAMP    NOT NULL,
    CONSTRAINT fk_attachments_task FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE
);

CREATE INDEX idx_tasks_due_date ON tasks (due_date);
CREATE INDEX idx_tasks_priority ON tasks (priority);
CREATE INDEX idx_task_attachments_task_id ON task_attachments (task_id);